version: '3.8'
services:
  springboot-app:
    image: springdocker
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://database:3306/springboot
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - database

  database:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=springboot

  react-frontend:
    image: reactdocker
    ports:
      - "3000:3000"

